feat: Pre-login Exploration Enrolment Handling
openedx/openedx-app-android pull request #169
Opened 2023-12-18 12:49 UTC by farhan-arshad-dev

### Pre-login Exploration Enrolment Handling

- Tapping the enroll button should lead the user to the logistration screen.
- On successfully logging in or registering the user should return to the course about page in the native experience.
- There needs to be a sticky bottom banner having the register and sign-in buttons a they explore discovery without logging in.

[Screen_recording_20231218_174011.webm](https://github.com/openedx/openedx-app-android/assets/43750646/311fd5f9-dd09-4dc1-ad2d-4bc5cca2e2b7)

2023-12-20 09:38 UTC, volodymyr-chekyrta commented on app/src/main/java/org/openedx/app/MainFragment.kt
> +        }
We can change `arguments?.let {}` to `requireArguments` if we always create MainFragment via newInstance()

2023-12-20 09:43 UTC, volodymyr-chekyrta commented on whatsnew/src/main/java/org/openedx/whatsnew/presentation/whatsnew/WhatsNewFragment.kt
> +                        router.navigateToMain(parentFragmentManager, null)
How about setting the `courseId` argument to null as the default value?

```fun navigateToMain(fm: FragmentManager, courseId: String? = null)```

2023-12-20 14:07 UTC, omerhabib26 commented
I have started its review 💻

2023-12-21 23:13 UTC, omerhabib26 requested changes
The App is working fine as expected only some code improvements and suggestions.

Edge Case: What will be the flow of Enroll in a course if a user sign-in through the discovery screen and what's new is enabled?

2023-12-21 23:13 UTC, omerhabib26 commented on app/src/main/java/org/openedx/app/MainFragment.kt
>  }
Please add a blank line at the EOF.

2023-12-26 22:40 UTC, omerhabib26 approved these changes
only a minor nit

2023-12-26 22:40 UTC, omerhabib26 commented on course/src/main/java/org/openedx/course/presentation/detail/CourseDetailsViewModel.kt
> +                        isUserLoggedIn = corePreferences.user != null
we can use `isUserLoggedIn`

2024-01-01 08:44 UTC, HamzaIsrar12 commented
Taking on PR responsibilities during Farhan's leave for personal reasons. Ready to handle communication and address queries.

2024-01-01 15:52 UTC, omerhabib26 approved these changes
LGTM 🚀

2024-01-02 06:38 UTC, merged