feat: redesign CourseDatesFragment
openedx/openedx-app-android pull request #172
Opened 2023-12-19 22:43 UTC by omerhabib26

### Description:

- Redesign CourseDatesFragment
- Restructure CourseDates Data
- Added minor utility methods

fix: LEARNER-9714

| Light Theme  | Dark Theme |
| ------------- | ------------- |
| <video src="https://github.com/openedx/openedx-app-android/assets/30689349/468280fd-7f0f-49f1-ab15-b595d0783891"  height = 480/>  |<video src="https://github.com/openedx/openedx-app-android/assets/30689349/7d0a2bf8-77f2-45fa-be43-e933a4291c31"/>  |

2023-12-20 09:49 UTC, volodymyr-chekyrta commented on core/src/main/java/org/openedx/core/utils/TimeUtils.kt
> +            daysDifference in -2 downTo -7 -> "${-daysDifference} days ago"
Let's move these strings to resources to localize them later.

2023-12-20 09:52 UTC, volodymyr-chekyrta commented
LGTM 👍👍👍
Need to fix only hardcoded strings.

2023-12-20 15:07 UTC, volodymyr-chekyrta commented on core/src/main/java/org/openedx/core/domain/model/DatesSection.kt
> +    NONE("none");
We should move these to strings as well

2023-12-20 20:31 UTC, k1rill reviewed
Good job, just nits. Only timeUtils need attention.

2023-12-20 20:31 UTC, k1rill commented on core/src/main/java/org/openedx/core/utils/TimeUtils.kt
> +
Please take a look on https://developer.android.com/reference/android/text/format/DateUtils class. It has it's own implementation of some methods, also it use android core localisation. Maybe we can use it

2023-12-20 20:31 UTC, k1rill commented on course/src/main/java/org/openedx/course/presentation/dates/CourseDatesFragment.kt
> +                                            .padding(start = 16.dp, end = 16.dp),
nit: .padding(horizontal = 16.dp)

2023-12-20 20:31 UTC, k1rill commented on course/src/main/java/org/openedx/course/presentation/dates/CourseDatesFragment.kt
> +                text = (if (dateBlock.assignmentType.isNullOrEmpty()
very hard to read this code, maybe you can try something like this:
```
text = if (dateBlock.assignmentType.isNullOrEmpty().not()) {
    "${dateBlock.assignmentType}: ${dateBlock.title}"
} else {
    dateBlock.title
},
```

2023-12-22 09:15 UTC, volodymyr-chekyrta commented on core/src/main/java/org/openedx/core/domain/model/DatesSection.kt
> +    fun getTitle(context: Context): String {
The DatesSection enum is located at the domain level, maybe it would be more correct to use ResourceManager instead of Android Context?

2023-12-22 09:51 UTC, k1rill approved these changes

2023-12-26 09:55 UTC, volodymyr-chekyrta approved these changes

2023-12-26 09:58 UTC, k1rill commented on course/src/main/java/org/openedx/course/presentation/dates/CourseDatesFragment.kt
> +                        text = sectionDates.size.toString() + " Items Hidden",
I suppose this should be in the resources too

2023-12-26 10:59 UTC, k1rill approved these changes
Approved from my side, good job!

2023-12-27 08:17 UTC, volodymyr-chekyrta approved these changes

2024-01-01 09:15 UTC, HamzaIsrar12 commented
Back from vacations and ready to start the review. 🚀

2024-01-02 06:48 UTC, HamzaIsrar12 requested changes

2024-01-02 06:48 UTC, HamzaIsrar12 commented on core/src/main/java/org/openedx/core/data/model/CourseDates.kt
> +        }
[Decision] Consider Date only. This means we should not use comparator operators.

2024-01-02 19:24 UTC, omerhabib26 commented on core/src/main/java/org/openedx/core/domain/model/DatesSection.kt
> +package org.openedx.core.domain.model
`Course` module doesn't contain any data or enum class

2024-01-02 19:25 UTC, omerhabib26 commented on core/src/main/java/org/openedx/core/ui/theme/Colors.kt
> +val dark_text_dark = Color.White
there was a mistake with color theming as we are using same text color in both modes

2024-01-03 06:37 UTC, HamzaIsrar12 commented on core/src/main/java/org/openedx/core/domain/model/DatesSection.kt
> +package org.openedx.core.domain.model
We can move it to `course/domain/model/` as it has no use in the Core module for now.

2024-01-03 07:46 UTC, HamzaIsrar12 approved these changes
LGTM 🏎️ ✨

2024-01-03 07:48 UTC, merged