feat: agreement urls
openedx/openedx-app-android pull request #174
Opened 2023-12-20 08:05 UTC by k1rill

Configuration fields added:

```
AGREEMENT_URLS:
  PRIVACY_POLICY_URL: ''
  COOKIE_POLICY_URL: ''
  DATA_SELL_CONSENT_URL: ''
  TOS_URL: ''
  EULA_URL: ''
  SUPPORTED_LANGUAGES: [ ] #en is defalut language
```

For `SUPPORTED_LANGUAGES` we are adding lang to the url path

If configuration field is empty, button will be hided in profile.

https://github.com/openedx/openedx-app-android/assets/1063094/28b55327-05d5-49a9-9d17-03e2378393ac

2023-12-20 16:14 UTC, volodymyr-chekyrta submitted a review, later dismissed

2023-12-22 14:49 UTC, omerhabib26 commented
I'm currently reviewing this

2023-12-26 22:09 UTC, omerhabib26 requested changes
Hey @k1rill, Everything is working fine as expected only some minor nits. 
Also, I have a couple of inquiries:
1- When altering the app or device language during runtime, the URLs do not undergo any modification or update. Is this intended behavior?
2- Regarding the End User License Agreement (EULA), there appears to be no associated implementation. Should we display it on the Sign-In Page, similar to how it is presented in the edX App?
cc: @moiz994 @marcotuts @volodymyr-chekyrta

2023-12-27 11:15 UTC, moiz994 commented
> Hey @k1rill, Everything is working fine as expected only some minor nits. Also, I have a couple of inquiries: 1- When altering the app or device language during runtime, the URLs do not undergo any modification or update. Is this intended behavior? 2- Regarding the End User License Agreement (EULA), there appears to be no associated implementation. Should we display it on the Sign-In Page, similar to how it is presented in the edX App? cc: @moiz994 @marcotuts @volodymyr-chekyrta

Regarding the EULA link, I need to sync with compliance and Product at 2U to confirm implementation. I can create a separate ticket for this and we can do it in a separate PR.

2024-01-03 16:13 UTC, k1rill commented on core/src/main/res/values/strings.xml
> +    <string name="core_cookie_policy" translatable="false">Cookie policy</string>
After conversation we decided to keep this as is

2024-01-03 21:10 UTC, omerhabib26 commented
Just need to update the following string to `Sentance Case` else LGTM 🚀 
![Screenshot 2024-01-04 at 2 10 00 AM](https://github.com/openedx/openedx-app-android/assets/30689349/a8fe63b4-8640-43ba-a83c-5e45a9125211)

2024-01-03 21:13 UTC, omerhabib26 submitted a review, later dismissed
Only a minor nit

2024-01-04 11:45 UTC, volodymyr-chekyrta approved these changes

2024-01-04 11:54 UTC, omerhabib26 approved these changes

2024-01-04 12:16 UTC, merged