feat: added styling to CourseDateBlock
openedx/openedx-app-android pull request #194
Opened 2024-01-18 10:18 UTC by omerhabib26

### Description

- Added relative icons for each date type
- Added locked content description
- Improve code structuring
- Improve the time format to understand the remaining time & date better

Issue: [156](https://github.com/openedx/openedx-app-android/issues/156)

<img src="https://github.com/openedx/openedx-app-android/assets/30689349/1e51b0eb-ee92-40b1-b6b0-3a6f645f62b7" height=480/> <img src="https://github.com/openedx/openedx-app-android/assets/30689349/5a2f57f6-ea71-46af-9cf7-a13fd2009042" height=480/>

2024-01-18 22:13 UTC, sdaitzman commented
@omerhabib26 this is looking great, thank you! I noticed two small design issues, hopefully we can resolve these without too much difficulty.

- The Completed Items collapsible block looks like it has around a 3px border, which should be thinner (1px). I think the thicker border draws a bit too much focus on this screen to that box.
- The gray subtext for verification-locked items matches the current Figma designs, but on reviewing this screenshot I noticed it looks a bit hard to read. I checked the contrast ratio and found it's too low to meet accessibility guidelines, so we should update this subtext to the Secondary Dark color in light mode. I've updated the designs in Figma to reflect this change.
<img width="637" alt="A screenshot of a contrast ratio checker showing a contrast ratio of 2.49 for the existing labels, which does not pass the WCAG accessibility guidelines" src="https://github.com/openedx/openedx-app-android/assets/1499476/0b3f5e82-9c13-4717-97e0-08d122f35dbc">

2024-01-23 12:17 UTC, farhan-arshad-dev requested changes

2024-01-23 12:17 UTC, farhan-arshad-dev commented on course/src/main/java/org/openedx/course/presentation/dates/CourseDatesFragment.kt
> +                    painter = painterResource(id = if (dateBlock.learnerHasAccess.not()) coreR.drawable.core_ic_lock else icon),
not sure but I think there should be use of `VERIFIED_UPGRADE_DEADLINE` and `VERIFICATION_DEADLINE_DATE`.

2024-01-23 12:17 UTC, farhan-arshad-dev commented on core/src/main/java/org/openedx/core/data/model/DateType.kt
> +    VERIFICATION_DEADLINE_DATE(R.drawable.core_ic_start_end),
Also, no use case is defined for these types.

2024-01-23 12:17 UTC, farhan-arshad-dev commented on course/src/main/java/org/openedx/course/presentation/dates/CourseDatesFragment.kt
> +            Spacer(modifier = Modifier.width(7.dp))
Not getting the effect of this spacer for me.

2024-01-23 12:17 UTC, farhan-arshad-dev commented on course/src/main/java/org/openedx/course/presentation/dates/CourseDatesFragment.kt
> +                    title = "Homework 1: A B C D",
no need to update mock date titles, can be reverted.

2024-01-23 12:21 UTC, omerhabib26 commented on core/src/main/java/org/openedx/core/data/model/DateType.kt
>      TODAY_DATE,
this type is no longer needed

2024-01-24 12:09 UTC, k1rill approved these changes
Approved from my side

2024-01-25 06:25 UTC, farhan-arshad-dev approved these changes

2024-01-25 08:19 UTC, volodymyr-chekyrta approved these changes
🚀

2024-01-25 09:51 UTC, merged