Social signup
openedx/openedx-app-android pull request #208
Opened 2024-01-24 07:46 UTC by k1rill

Added social auth buttons to the registration screen.

Social auth should be configured in the config.yaml before.

https://github.com/openedx/openedx-app-android/assets/1063094/f26d4688-1178-4696-8b03-156cd6b8c56d

2024-01-26 05:50 UTC, farhan-arshad-dev commented
Starting review.

2024-01-26 05:50 UTC, farhan-arshad-dev commented
@k1rill test cases are still failing.

2024-01-26 07:47 UTC, k1rill commented
> @k1rill test cases are still failing.

@farhan-arshad-dev thank you for report. I just updated PR with tests fix and resolving conflicts

2024-01-30 10:02 UTC, volodymyr-chekyrta commented
I've started review

2024-01-30 19:00 UTC, farhan-arshad-dev requested changes
Just some minor improvements. btw thank you for the well-written code. It was a pleasure to review. 🔥

2024-02-05 08:43 UTC, k1rill commented on auth/src/main/java/org/openedx/auth/presentation/sso/GoogleAuthHelper.kt
> +                } else {
can you please explain what do you mean? 
This was added according to official documentation: https://developer.android.com/training/sign-in/credential-manager#sign-in

2024-02-06 07:27 UTC, farhan-arshad-dev commented on auth/src/main/java/org/openedx/auth/presentation/sso/GoogleAuthHelper.kt
> +                } else {
just need an official doc for the ref, and better to add in the code as the docstring.

2024-02-07 11:14 UTC, miankhalid commented on auth/src/main/java/org/openedx/auth/presentation/signup/compose/SocialSignedView.kt
> +        )
plz coordinate with @bilalawan321 in this regard, thanks!

2024-02-09 12:51 UTC, hassan6190 commented
@k1rill @farhan-arshad-dev, I have tested out the social logins and they are working as expected apart from some of the following issues below 

- While login with a new user (Gmail), the user gets an error message “Something went wrong“ instead of “this user is not linked with any edX account“
-  When a user login or register through Facebook it shows 2 loaders at the same time 

**Note:** Please see the attached video for the issues

Uploading Screen_Recording_20240209-173139_edX.mp4…

2024-02-09 14:17 UTC, farhan-arshad-dev commented on auth/src/main/java/org/openedx/auth/presentation/signup/compose/SocialSignedView.kt
> +        )
I have discussed with @bilalawan321 regarding the `resource_id`, confirming that they are already in place and no changes are necessary.

2024-02-11 13:07 UTC, k1rill commented
> @k1rill @farhan-arshad-dev, I have tested out the social logins and they are working as expected apart from some of the following issues below
> 
> * While login with a new user (Gmail), the user gets an error message “Something went wrong“ instead of “this user is not linked with any edX account“
> * When a user login or register through Facebook it shows 2 loaders at the same time
> 
> **Note:** Please see the attached video for the issues
> 
>  Screen_Recording_20240209-173139_edX.mp4

thank you @hassan6190, can you please open issues for this, this PR is for Sign Up pages only, sign in was merged in https://github.com/openedx/openedx-app-android/pull/89

2024-02-12 06:12 UTC, bilalawan321 commented on auth/src/main/java/org/openedx/auth/presentation/signup/compose/SocialSignedView.kt
> +        )
Yes, I have checked the signup page, and the `resource_id` is located within the social authentications.

2024-02-12 06:59 UTC, farhan-arshad-dev commented on auth/src/main/java/org/openedx/auth/presentation/signin/compose/SignInView.kt
> +            SocialAuthView(
still pending.

2024-02-12 07:02 UTC, farhan-arshad-dev commented on auth/src/main/java/org/openedx/auth/presentation/signup/SignUpViewModel.kt
> +    }
still pending.

2024-02-12 07:03 UTC, farhan-arshad-dev commented on auth/src/main/java/org/openedx/auth/presentation/ui/SocialAuthView.kt
> +    isSignIn: Boolean = false,
pending.

2024-02-12 07:04 UTC, k1rill commented on auth/src/main/java/org/openedx/auth/presentation/signup/SignUpViewModel.kt
> +    }
is this required? can you please explain profit of this?

2024-02-12 07:11 UTC, k1rill commented on auth/src/main/java/org/openedx/auth/presentation/signin/compose/SignInView.kt
> +            SocialAuthView(
sorry forgot to include this in the last commit, just updated

2024-02-12 07:13 UTC, k1rill commented on auth/src/main/java/org/openedx/auth/presentation/sso/OAuthHelper.kt
> +            AuthType.MICROSOFT -> microsoftAuthHelper.socialAuth(fragment.requireActivity())
Our QA team was tested this feature comparing with the current prod app, and didn't found any case where we should do logout. Can you please add an example, how can we test this?

2024-02-12 07:33 UTC, k1rill commented on auth/src/main/java/org/openedx/auth/presentation/signup/SignUpViewModel.kt
> +    }
it's hard to rewrite this, because exchangeToken has different logic for sign in and sign up

2024-02-12 07:38 UTC, farhan-arshad-dev commented on auth/src/main/java/org/openedx/auth/presentation/sso/OAuthHelper.kt
> +            AuthType.MICROSOFT -> microsoftAuthHelper.socialAuth(fragment.requireActivity())
pending.

2024-02-12 07:41 UTC, farhan-arshad-dev commented on auth/src/main/java/org/openedx/auth/presentation/signup/SignUpViewModel.kt
> +    }
mainly the code is the extension of the `Social AuthResponse`, so my recommendation is to move in the `Social AuthResponse` class, as there is complexity to rewrite we can leave it for now.

2024-02-12 08:15 UTC, farhan-arshad-dev approved these changes

2024-02-12 08:21 UTC, volodymyr-chekyrta commented
> @k1rill @farhan-arshad-dev, I have tested out the social logins and they are working as expected apart from some of the following issues below
> 
> * While login with a new user (Gmail), the user gets an error message “Something went wrong“ instead of “this user is not linked with any edX account“
> * When a user login or register through Facebook it shows 2 loaders at the same time
> 
> **Note:** Please see the attached video for the issues
> 
>  Screen_Recording_20240209-173139_edX.mp4

It would be nice to hide the whole button section on data loading.
But this can be addressed separately.

2024-02-12 08:21 UTC, volodymyr-chekyrta approved these changes

2024-02-12 08:22 UTC, merged