fix: Draft PR for element IDs
openedx/openedx-app-android pull request #214
Opened 2024-01-31 12:36 UTC by omerhabib26

2024-02-02 17:33 UTC, farhan-arshad-dev requested changes

2024-02-12 12:46 UTC, farhan-arshad-dev approved these changes
just some nits.

2024-02-12 12:46 UTC, farhan-arshad-dev commented on profile/src/main/java/org/openedx/profile/presentation/edit/EditProfileFragment.kt
> -
why need this code deletion?

2024-02-12 12:46 UTC, farhan-arshad-dev commented on core/src/main/java/org/openedx/core/extension/StringExt.kt
> +fun String.replaceSpaces(target: String = ""): String = this.replace(" ", target)
better to remove it with `replaceSpace`

2024-02-12 15:55 UTC, omerhabib26 commented on profile/src/main/java/org/openedx/profile/presentation/edit/EditProfileFragment.kt
> -
it was unused

2024-02-12 15:58 UTC, omerhabib26 commented on profile/src/main/java/org/openedx/profile/presentation/edit/EditProfileFragment.kt
> -
it was unused

2024-02-13 06:00 UTC, farhan-arshad-dev approved these changes

2024-02-15 06:44 UTC, farhan-arshad-dev approved these changes

2024-02-15 06:59 UTC, merged