fix: bug when data is not displayed on the Hangouts and Announcement
openedx/openedx-app-android pull request #242
Opened 2024-02-28 18:03 UTC by dixidroid

Fixed next bug:

<img width="373" alt="Снимок экрана 2024-02-28 в 18 56 30" src="https://github.com/openedx/openedx-app-android/assets/5153976/047a18f9-aabf-4797-af84-fe06394a4556">

it occurred due to the inability to update the URL in the WebView

2024-02-28 20:42 UTC, omerhabib26 requested changes
Hey @dixidroid, please show a proper msg in case of no handouts or announcements are available.



<img height="351" alt="Screenshot 2024-02-29 at 1 41 48 AM" src="https://github.com/openedx/openedx-app-android/assets/30689349/3dafd4d1-1af3-4ca3-b1dc-c16e7e15c320">

2024-02-29 09:27 UTC, volodymyr-chekyrta approved these changes

2024-02-29 11:52 UTC, dixidroid commented
Hi @omerhabib26, I don't think this applies to the current bug. We will create another ticket for this.

2024-02-29 12:18 UTC, omerhabib26 commented
> Hi @omerhabib26, I don't think this applies to the current bug. We will create another ticket for this.

@moiz994 Please create a ticket for this.

2024-02-29 12:18 UTC, omerhabib26 approved these changes

2024-02-29 12:34 UTC, k1rill approved these changes

2024-02-29 12:34 UTC, merged