fix: bug when sequence units level appear after tapping back
openedx/openedx-app-android pull request #260
Opened 2024-03-15 10:02 UTC by dixidroid

Removed sequence units level when open a content from Resume or Dates

2024-03-17 22:29 UTC, HamzaIsrar12 requested changes
We need to make changes while considering the `COURSE_NESTED_LIST_ENABLED` flag, accounting for both true and false values.

Previously, it functioned correctly with the `false` value, but now it operates with the `true` value. Let's account for both scenarios this time. 😄

2024-03-18 11:27 UTC, dixidroid commented
@HamzaIsrar12 so, when COURSE_NESTED_LIST_ENABLED = false when an user clicks the resume button the next content will be opened and then when he goes back the list of units should appear? Don't think this is a good behaviour...thoughts?

2024-03-18 20:33 UTC, HamzaIsrar12 commented
@dixidroid 
It's a reasonable approach. If it seems incomplete, it might be because we previously highlighted the relevant unit on back press, providing a visual cue for the user to identify the unit they were on.

2024-03-19 14:43 UTC, dixidroid commented
@HamzaIsrar12 I've added an ability to use the COURSE_NESTED_LIST_ENABLED flag

2024-03-21 04:41 UTC, HamzaIsrar12 approved these changes
LGTM 🏎️ ✨

2024-03-21 04:41 UTC, HamzaIsrar12 commented on course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineFragment.kt
>                          viewModel.resumeSectionBlock?.let { subSection ->
We can also move this and the other block (in DatesFragment) to their respective ViewModel, but that's up to you now. 😄

2024-03-21 09:28 UTC, volodymyr-chekyrta approved these changes

2024-03-21 16:32 UTC, k1rill approved these changes

2024-03-21 16:32 UTC, merged