feat: Minor UI changes
openedx/openedx-app-android pull request #266
Opened 2024-03-21 12:36 UTC by PavloNetrebchuk

Changes according to this document:
https://www.figma.com/file/iZ56YMjbRMShCCDxqrqRrR/Open-edX-Mobile-App-All-Screens-v2.1?type=design&node-id=9980-2&mode=design&t=m8EjlsKk0aI9cQe8-0
<img width="464" alt="Screenshot 2024-03-21 at 14 29 19" src="https://github.com/openedx/openedx-app-android/assets/141041606/64ac2979-9d23-4e8a-aa6b-0a3895d4005e">
<img width="465" alt="Screenshot 2024-03-21 at 14 29 53" src="https://github.com/openedx/openedx-app-android/assets/141041606/95063d6e-d627-458d-9b9f-635d1f5ab30a">
<img width="463" alt="Screenshot 2024-03-21 at 14 30 13" src="https://github.com/openedx/openedx-app-android/assets/141041606/f3ebbfd3-0980-4d31-9f02-d445395d0793">
<img width="463" alt="Screenshot 2024-03-21 at 14 30 57" src="https://github.com/openedx/openedx-app-android/assets/141041606/1d8adc03-5607-474f-97c8-e1e3aace495b">
<img width="463" alt="Screenshot 2024-03-21 at 14 31 58" src="https://github.com/openedx/openedx-app-android/assets/141041606/58bd84f6-e4a4-4760-a08a-848b4c75dd88">

2024-03-25 11:14 UTC, volodymyr-chekyrta submitted a review, later dismissed

2024-03-25 15:35 UTC, PavloNetrebchuk commented
@sdaitzman 
<img width="314" alt="Screenshot 2024-03-25 at 17 32 25" src="https://github.com/openedx/openedx-app-android/assets/141041606/c0f3b3ac-5c9d-4d43-b993-2ed14708daa1">
Done

2024-03-26 06:39 UTC, k1rill submitted a review, later dismissed

2024-03-26 11:18 UTC, omerhabib26 requested changes
Some minor code changes and improvements

2024-03-26 11:18 UTC, omerhabib26 commented on core/src/main/java/org/openedx/core/ui/ComposeCommon.kt
> +                        painter = painterResource(R.drawable.core_ic_close),
we can use `imageVector = Icons.Filled.Close,` instead, and remove this drawable.

2024-03-26 11:18 UTC, omerhabib26 commented on core/src/main/res/drawable/core_ic_close.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
we can remove this and use `imageVector = Icons.Filled.Close,`

2024-03-26 11:18 UTC, omerhabib26 commented on core/src/main/res/drawable/core_no_internet_connection.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
requires auto-format.

2024-03-26 11:18 UTC, omerhabib26 commented on core/src/main/res/drawable/core_ic_reload.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
1- can we use white color as a strokeColor to make it more generic?
2- requires auto-format

2024-03-26 11:18 UTC, omerhabib26 commented on core/src/main/res/drawable/core_ic_offline.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
1- can we use white color as a strokeColor to make it more generic?
2- requires auto-format

2024-03-26 11:18 UTC, omerhabib26 commented on course/src/main/res/drawable/course_ic_not_supported_block.xml
>      android:height="100dp"
1- can we use white color as a strokeColor to make it more generic?
2- requires auto-format

2024-03-27 09:46 UTC, PavloNetrebchuk commented
@omerhabib26 Changed and formatted👍

2024-03-27 14:17 UTC, omerhabib26 approved these changes

2024-03-27 14:32 UTC, volodymyr-chekyrta approved these changes

2024-03-27 14:32 UTC, merged