fix: typos
openedx/openedx-app-android pull request #310
Opened 2024-05-03 15:14 UTC by volodymyr-chekyrta

2024-05-05 21:19 UTC, HamzaIsrar12 requested changes
Another nit spotted by GPT in the `ConfigurationManagement` 😄 

"Could Messaging" should be corrected to "Cloud Messaging"

2024-05-06 08:52 UTC, k1rill approved these changes

2024-05-06 09:14 UTC, volodymyr-chekyrta commented
> Another nit spotted by GPT in the `ConfigurationManagement` 😄
> 
> "Could Messaging" should be corrected to "Cloud Messaging"

@HamzaIsrar12, Thanks for pointing that out!
Fixed ✅

2024-05-06 09:30 UTC, HamzaIsrar12 approved these changes

2024-05-06 10:19 UTC, merged

2024-05-06 10:19 UTC, openedx-webhooks commented
@volodymyr-chekyrta 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-app-android&entry.867055334=https://github.com/openedx/openedx-app-android/pull/310&entry.1484655318=https://github.com/volodymyr-chekyrta&entry.752974735=2024-05-03+15:14&entry.1917517419=2024-05-06+10:19&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->