Feat: Calendar main screen and dialogs
openedx/openedx-app-android pull request #322
Opened 2024-05-17 14:08 UTC by PavloNetrebchuk

https://www.figma.com/design/iZ56YMjbRMShCCDxqrqRrR/Open-edX-Mobile-App-All-Screens-v2.1?node-id=13749-57827&t=1CiKfcW4o1pmVC5G-0

2024-05-17 14:08 UTC, openedx-webhooks commented
Thanks for the pull request, @PavloNetrebchuk! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2024-05-20 10:24 UTC, volodymyr-chekyrta requested changes

2024-05-20 10:24 UTC, volodymyr-chekyrta commented on core/src/main/java/org/openedx/core/presentation/dialog/DialogUI.kt
> +}
New line at the end of the file

2024-05-20 10:24 UTC, volodymyr-chekyrta commented on profile/src/main/java/org/openedx/profile/presentation/calendar/CalendarAccessDialogFragment.kt
> +}
New line at the end of the file

2024-05-20 10:24 UTC, volodymyr-chekyrta commented on profile/src/main/java/org/openedx/profile/presentation/calendar/CalendarColor.kt
> +}
New line at the end of the file

2024-05-20 10:45 UTC, PavloNetrebchuk commented
The CalendarManager and several calendar logic classes were moved to the core module to save the efficiency of the dates tab on the course home screen. We will move them back after adding a new calendar setting and removing the dates tab.

2024-05-20 11:21 UTC, volodymyr-chekyrta approved these changes

2024-05-21 14:34 UTC, volodymyr-chekyrta commented
@HamzaIsrar12 @k1rill friendly reminder on this PR 🙏
We have to unblock further work.

2024-05-24 09:13 UTC, k1rill reviewed
Great, just minor nits from my side

2024-05-24 09:13 UTC, k1rill commented on core/src/main/java/org/openedx/core/config/Config.kt
> +        private const val API_APP_ID = "APPLICATION_ID"
just strange name of the constant API_APP_ID maybe we can use APPLICATION_ID?

2024-05-24 09:13 UTC, k1rill commented on profile/src/main/java/org/openedx/profile/presentation/calendar/CalendarAccessDialogFragment.kt
> +        if (dialog != null && dialog!!.window != null) {
Can be simplified without if to:
`dialog?.window?.setBackgroundDrawable(ColorDrawable(Color.TRANSPARENT))`

2024-05-24 09:13 UTC, k1rill commented on profile/src/main/java/org/openedx/profile/presentation/calendar/CalendarFragment.kt
> +                NewCalendarDialogFragment::class.simpleName
it's better to use constants here, because class names could be obfuscated on the prod builds

2024-05-24 09:13 UTC, k1rill commented on profile/src/main/java/org/openedx/profile/presentation/calendar/NewCalendarDialogFragment.kt
> +        if (dialog != null && dialog!!.window != null) {
the same with a comment above

2024-05-24 09:13 UTC, k1rill commented on profile/src/main/java/org/openedx/profile/presentation/calendar/NewCalendarDialogFragment.kt
> +                        //TODO
please write what exactly we should add here in future, or remove

2024-05-24 09:13 UTC, k1rill commented on profile/src/main/java/org/openedx/profile/presentation/settings/SettingsViewModel.kt
> +
empty line

2024-05-24 10:42 UTC, PavloNetrebchuk commented
@k1rill I've completed it. Could you please review it again at your earliest convenience?

2024-05-24 11:07 UTC, k1rill approved these changes
LGTM

2024-05-24 11:27 UTC, volodymyr-chekyrta commented
Thank you guys!

2024-05-27 06:53 UTC, HamzaIsrar12 requested changes
Minor nits only. ✨ 

_Maybe we need to introduce a feature flag as well for the app-level calendar sync feature._

2024-05-27 07:01 UTC, volodymyr-chekyrta commented
> _Maybe we need to introduce a feature flag as well for the app-level calendar sync feature._

Just for clarification 🤓
By FC-0047 the app level calendar should replace the course level calendar.

2024-05-27 13:29 UTC, PavloNetrebchuk commented on profile/src/main/java/org/openedx/profile/presentation/calendar/CalendarColor.kt
> +    ACCENT(R.string.calendar_color_accent, 0xFFD13329),
I believe it is unnecessary as those colors are constants and do not depend on the theme. Also, the YELLOW cannot become red after restyling.

2024-05-27 13:44 UTC, PavloNetrebchuk commented
@HamzaIsrar12 
Thanks for your feedback! I've added the recent changes.

2024-05-29 09:07 UTC, HamzaIsrar12 approved these changes
LGTM  🏎️ ✨

2024-05-29 10:03 UTC, merged

2024-05-29 10:03 UTC, openedx-webhooks commented
@PavloNetrebchuk 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-app-android&entry.867055334=https://github.com/openedx/openedx-app-android/pull/322&entry.1484655318=https://github.com/PavloNetrebchuk&entry.752974735=2024-05-17+14:08&entry.1917517419=2024-05-29+10:03&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->