feat: Fullstory Analytics SDK Implementation
openedx/openedx-app-android pull request #347
Opened 2024-06-20 22:52 UTC by HamzaIsrar12

### Description

[LEARNER-10041](https://2u-internal.atlassian.net/browse/LEARNER-10041)

We have introduced the Fullstory Analytics Provider, which includes three main methods:

**Identify:** This method identifies the user by passing a userID (uid). Additionally, it includes a displayName for use on the Fullstory dashboard.

**Event:** This method records custom app events.

**Page:** This method functions similarly to a screen event, tracking page views.

### Config:
```
FULLSTORY:
  ENABLED: false
  ORG_ID: ''
```

### References:

- [Getting Started with Android Data Capture](https://help.fullstory.com/hc/en-us/articles/360040596093-Getting-Started-with-Android-Data-Capture)
- [Fullstory for Android - API Overview](https://developer.fullstory.com/mobile/android/)

---

### Page or Screen Events

We have reorganized our event tracking by moving certain events from custom events to screen or page events. Below are the updated screen or page events:

- Launch
- Logistration:Sign In (new)
- Logistration:Register (new)
- MainDashboard:My Courses
- MainDashboard:My Programs
- MainDashboard:Discover
- MainDashboard:Profile
- Profile:Edit Profile (new)
- Course:Dashboard
- Course:Home Tab
- Course:Videos Tab
- Course:Discussion Tab
- Course:Dates Tab
- Course:Handouts Tab
- Course:Announcements
- Course:Handouts
- Discovery:Course Info
- Discovery:Program Info

2024-06-21 20:04 UTC, volodymyr-chekyrta commented
To flag, we can merge it for now.
But it's not a widely used instrument, it will be removed from the Open edX repo and should be used as a plug-in in the future.

2024-06-24 18:58 UTC, omerhabib26 commented
Reviewing

2024-07-01 17:23 UTC, omerhabib26 requested changes
only some minor nits,
Some test cases are failing in `VideoUnitViewModelTest.kt`

2024-07-01 17:23 UTC, omerhabib26 commented on dashboard/src/main/java/org/openedx/learn/presentation/LearnViewModel.kt
> +        analytics.logScreenEvent(event.eventName,
please mention parameters name

2024-07-03 17:49 UTC, omerhabib26 approved these changes

2024-07-09 13:36 UTC, merged