fix: update keyboard visibility and imeAction
openedx/openedx-app-android pull request #350
Opened 2024-06-24 18:15 UTC by omerhabib26

### Description

- Hide keyboard on logistration screens
- update imeAction for long InputEditFields

-LEARNER-10032

2024-06-25 06:55 UTC, volodymyr-chekyrta approved these changes

2024-07-03 09:57 UTC, HamzaIsrar12 requested changes
Minor nits only

2024-07-03 09:57 UTC, HamzaIsrar12 commented on auth/src/main/java/org/openedx/auth/presentation/restore/RestorePasswordFragment.kt
> +                                        isEmailError = email.isEmpty()
On value change, the error should be removed.

```suggestion
                                        isEmailError = false
```

2024-07-03 09:57 UTC, HamzaIsrar12 commented on auth/src/main/java/org/openedx/auth/presentation/signin/compose/SignInView.kt
> +
Please remove extra line.

2024-07-03 09:57 UTC, HamzaIsrar12 commented on auth/src/main/java/org/openedx/auth/presentation/signin/compose/SignInView.kt
> +                isEmailError = login.isEmpty()
```suggestion
                isEmailError = false
```

2024-07-03 09:57 UTC, HamzaIsrar12 commented on auth/src/main/java/org/openedx/auth/presentation/signin/compose/SignInView.kt
> +                isPasswordError = password.isEmpty()
```suggestion
                isPasswordError = false
```

2024-07-03 23:37 UTC, HamzaIsrar12 approved these changes

2024-07-08 10:21 UTC, volodymyr-chekyrta approved these changes
LGTM

2024-07-08 10:21 UTC, merged