refactor: Improve customAppColors usage according to usage
openedx/openedx-app-android pull request #356
Opened 2024-06-28 14:37 UTC by omerhabib26

### Description:

- refactor app design to efficiently handle customAppColor variables

fix: LEARNER-10043

2024-07-03 18:52 UTC, dixidroid submitted a review, later dismissed
LGTM

2024-07-09 13:11 UTC, HamzaIsrar12 requested changes

2024-07-10 21:04 UTC, HamzaIsrar12 approved these changes

2024-07-16 10:02 UTC, dixidroid approved these changes

2024-07-24 10:50 UTC, omerhabib26 commented
We're closing this PR and moving these changes to our own fork, as they are critical for us. After our release, we hope to find a way to contribute these changes back, thanks!

2024-07-24 10:50 UTC, closed without merging