feat: App Level Webview/No Internet Error Handling
openedx/openedx-app-android pull request #357
Opened 2024-07-05 07:19 UTC by farhan-arshad-dev

### Description

- Not Internet Error Handling with reload CTA
- Unknown error while loading the web page with reload CTA.

fixes: LEARNER-10046

| Unknown error on web-page load | No Internet Connection (Reuse) |
| ------------- | ------------- |
| ![Screenshot_20240704_113753](https://github.com/openedx/openedx-app-android/assets/43750646/76837d26-5c16-4739-bec5-06b3faee83e0)  | ![Screenshot_20240705_120819](https://github.com/openedx/openedx-app-android/assets/43750646/546b469d-b839-4f0d-82eb-4085993c25a7)  |

2024-07-09 13:44 UTC, omerhabib26 requested changes
Some minor code changes and improvements.

2024-07-09 13:44 UTC, omerhabib26 commented on course/src/main/java/org/openedx/course/presentation/unit/html/HtmlUnitFragment.kt
> +                var isError by remember {
we can move this in ViewModel

2024-07-09 13:44 UTC, omerhabib26 commented on course/src/main/java/org/openedx/course/presentation/unit/html/HtmlUnitFragment.kt
> +                                    modifier = Modifier
we can move the modifier inside CommonCompose.

2024-07-09 13:44 UTC, omerhabib26 commented on discovery/src/main/java/org/openedx/discovery/presentation/program/ProgramFragment.kt
ErrorHandling not working on MyPrograms.

2024-07-15 11:52 UTC, omerhabib26 requested changes
Some minor code improvements.

2024-07-15 11:52 UTC, omerhabib26 commented on discovery/src/main/java/org/openedx/discovery/presentation/program/ProgramViewModel.kt
> -        replay = 0,
Any reason to remove this?

2024-07-15 11:52 UTC, omerhabib26 commented on discovery/src/main/java/org/openedx/discovery/presentation/catalog/CatalogWebView.kt
> +                    super.onReceivedError(view, request, error)
shouldn't we call this after if condition?

2024-07-15 11:52 UTC, omerhabib26 commented on discovery/src/main/java/org/openedx/discovery/presentation/WebViewDiscoveryViewModel.kt
>  package org.openedx.discovery.presentation
Requires auto-format

2024-07-15 11:52 UTC, omerhabib26 commented on discovery/src/main/java/org/openedx/discovery/presentation/WebViewDiscoveryViewModel.kt
> +    private val _uiState = MutableStateFlow<DiscoveryUIState>(DiscoveryUIState.Loading)
We can use `WebviewUIState` here as well.

2024-07-15 11:52 UTC, omerhabib26 commented on discovery/src/main/java/org/openedx/discovery/presentation/DiscoveryUIState.kt
> +    data object Loaded : DiscoveryUIState()
instead of adding new objects in DiscoveryUIState, we can use WebviewUIState

2024-07-15 11:52 UTC, omerhabib26 commented on discovery/src/main/java/org/openedx/discovery/presentation/info/CourseInfoUIState.kt
> +enum class CourseInfoUIAction {
We can define a generalised WebView State. here and other occurrences 
```
enum class WebPageState{
    WEB_PAGE_LOADED,
    WEB_PAGE_ERROR,
    RELOAD_WEB_PAGE
}

2024-07-15 11:52 UTC, omerhabib26 commented on discovery/src/main/java/org/openedx/discovery/presentation/WebViewDiscoveryFragment.kt
> +                        ErrorScreen(
we can simply call `ConnectionErrorView()`

2024-07-15 11:52 UTC, omerhabib26 commented on discovery/src/main/java/org/openedx/discovery/presentation/info/CourseInfoFragment.kt
> +                        ErrorScreen(
same here

2024-07-15 13:26 UTC, farhan-arshad-dev commented on core/src/main/java/org/openedx/core/ui/ComposeCommon.kt
> +    title: String,
as we introduce this function as common compose, IMO it's better not to couple it with some constant.

2024-07-15 13:33 UTC, farhan-arshad-dev commented on core/src/main/java/org/openedx/core/presentation/global/webview/WebViewState.kt
as it relates to whether the web view loaded the URL or not, IMO `WebViewState` is more appropriate.

2024-07-15 13:34 UTC, farhan-arshad-dev commented on course/src/main/java/org/openedx/course/presentation/unit/html/HtmlUnitUIState.kt
> +sealed class HtmlUnitUIState {
this is coupled with the UI screen, better to place separately.

2024-07-17 08:51 UTC, omerhabib26 requested changes
Connectivity error not handled on view all courses,
else only 2 minor nits,

2024-07-17 13:24 UTC, omerhabib26 approved these changes
LGTM

2024-07-17 14:00 UTC, farhan-arshad-dev commented
We're closing this PR and moving these changes to our own fork, as they are critical for us. After our release, we hope to find a way to contribute to these changes back, thanks!

2024-07-17 14:00 UTC, closed without merging