feat: Course Level Error Handling for Empty States
openedx/openedx-app-android pull request #363
Opened 2024-07-15 09:47 UTC by farhan-arshad-dev

### Description

- Empty state for Home, Videos, Dates, and Discussion tabs.
- Empty state for handouts, and Announcements screen.

fixes: LEARNER-10039

| Home Tab | Video Tab | Dates Tab |
| ------------- | ------------- | ------------- |
| <img src="https://github.com/user-attachments/assets/6e4c9dce-1950-4bf6-893d-5c62dbfe2eae"/> | <img src="https://github.com/user-attachments/assets/33603a32-bb6c-42c0-84f1-be8d1cc500de"/> | <img src="https://github.com/user-attachments/assets/2b11aee3-acb8-4423-adc3-a3ce2dffa6b6" /> |

| Discussion Tab | Handouts Screen | Announcements Screen |
| ------------- | ------------- | ------------- |
| <img src="https://github.com/user-attachments/assets/4f37a01b-1cb7-4031-a675-7dcf2415c170" /> | <img src="https://github.com/user-attachments/assets/acffd5fd-32ee-4cb2-a99e-48e9fdf0c8f9" /> | <img src="https://github.com/user-attachments/assets/c14ec4d5-0cf7-4332-a726-dc926dfdc9e1" /> |

2024-07-16 12:28 UTC, omerhabib26 requested changes
Some minor code improvements.

2024-07-16 12:28 UTC, omerhabib26 commented on course/src/main/res/drawable/course_ic_no_announcements.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
we can move these icons in core.

2024-07-16 12:28 UTC, omerhabib26 commented on course/src/main/res/drawable/course_ic_no_videos.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
same here

2024-07-16 12:28 UTC, omerhabib26 commented on discussion/src/main/java/org/openedx/discussion/presentation/topics/DiscussionTopicsScreen.kt
>                                  DiscussionTopicsUIState.Loading -> {}
Can we add CircularProgress for loading?

2024-07-17 16:39 UTC, dixidroid approved these changes

2024-07-17 17:43 UTC, omerhabib26 approved these changes
only a minor nit.

2024-07-17 17:43 UTC, omerhabib26 commented on discussion/src/main/res/values/strings.xml
> +
unused code

2024-07-18 05:33 UTC, farhan-arshad-dev commented
We're closing this PR and moving these changes to our own fork, as they are critical for us. After our release, we hope to find a way to contribute to these changes back, thanks!

2024-07-18 05:33 UTC, closed without merging